# This is an example of a credentials file that can be used with this app
# If you run `rails credentials:edit` for the first time, it will create
# a credentials.yml.enc file along with a master.key file. *Never* check in the
# master.key file to your repository, as it contains the key used to encrypt.
# By default, it may only create a top level hierarchy, but this app requires
# development, test, and production stages to be configured


# use 'securerandom' gem to create a secret per stage:
#   SecureRandom.hex(64)
# Note if you use environmental secret files, things will break
secret_key_base: "SECRET_STRING"

development:
  # MySQL Database Password
  db_password: "database password"
  # The RabbitMQ URL for the app to connect to
  amqp_url: "amqp://user:pass@127.0.0.1:5672"
  # The default admin user's password, which will be used when running db:reset
  default_admin_password: "super_secret_password"

test:
  db_password: "database password"
  amqp_url: "amqp://user:pass@127.0.0.1:5672"
  default_admin_password: "super_secret_password"

production:
  db_password: "database password"
  amqp_url: "amqp://user:pass@127.0.0.1:5672"
  default_admin_password: "super_secret_password"
